version: "3.8"
services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27027:27017"
    volumes:
      - ./database/db:/data/db

  backend:
    build:
      context: ./Backend
    container_name: backend_bookstore
    ports:
      - "3000:3000"
    links:
      - mongo


  frontend:
    build:
      context: ./Frontend
    container_name: frontend_bookstore
    ports:
      - "5173:5173"

networks:
  my-network: